modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/samolego/Taterzens/issues"
license = "MIT"

[[mods]]
modId = "taterzens"
version = "${version}"
displayName = "Taterzens"
displayURL="https://samolego.github.io/Taterzens"
authors = "samo_lego"
description = '''
A citizens like mod.
'''
logoFile = "icon.png"

[[dependencies.taterzens]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.taterzens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "SERVER"