site_name: Taterzens
site_url: https://samolego.github.io/Taterzens

repo_url: https://github.com/samolego/Taterzens
repo_name: samolego/Taterzens

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
  icon:
    logo: fontawesome/solid/users
    repo: fontawesome/brands/github
  favicon: assets/img/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: green
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: light green
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


plugins:
  - search
  - mike:
      version_selector: true   # set to false to leave out the version selector


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tilde # strikethrough text
  - pymdownx.details # "notes"
  - attr_list #images
 
extra:
  version:
    provider: mike
